name: self-air-routes
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - osmnx=1.9.2
  - pillow
  - pre-commit
  - python=3.11.*
  - python-igraph
  - folium==0.16.0
  - geopy==2.4.1
  - ipython==8.12.3
  - ipython==7.31.1
  - networkx==3.2.1
  - networkx==2.4
  - numpy==1.21.5
  - osmnx==1.9.2
  - pandas==2.2.2
