name: selfairroutes
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - osmnx=1.9.2
  - pillow
  - pre-commit
  - python
  - python-igraph
  - folium
  - geopy
  - ipython
  - ipython
  - networkx
  - networkx
  - numpy
  - osmnx
  - pandas
